<a href="https://colab.research.google.com/github/Donthula-Harika/Deep-Learning/blob/main/Artificial_Neural_Networks/car_price_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- Load CSV files ---
df = pd.read_csv("/content/drive/MyDrive/Data Sets/CarPrice_dataset.csv")
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [ ]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [ ]:
from pandas.core.arrays import categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

X = df.drop(columns = 'price')
y = df['price']

#Identify categorical n numerical col
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Define preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ]
)

# Apply preprocessing
X_processed = preprocessor.fit_transform(X)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42
)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Build ANN model
model = Sequential([
    Dense(512, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

# Model summary
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │       102,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 277,505 (1.06 MB)

 Trainable params: 277,505 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:

# Compile model
model.compile(
    optimizer='adam',
    loss='mean_absolute_error',
    metrics=['mean_absolute_error','mean_squared_error']
)

In [ ]:
# Train model
history = model.fit(
    X_train,
    y_train,
    epochs=70,
    verbose=1,
    validation_split=0.2
)

Epoch 1/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 8s 525ms/step - loss: 12623.9336 - mean_absolute_error: 12623.9336 - mean_squared_error: 209686400.0000 - val_loss: 15081.4570 - val_mean_absolute_error: 15081.4570 - val_mean_squared_error: 317892672.0000
Epoch 2/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 12914.1104 - mean_absolute_error: 12914.1104 - mean_squared_error: 219772240.0000 - val_loss: 15076.1543 - val_mean_absolute_error: 15076.1543 - val_mean_squared_error: 317724768.0000
Epoch 3/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 12750.6904 - mean_absolute_error: 12750.6904 - mean_squared_error: 213075776.0000 - val_loss: 15059.8145 - val_mean_absolute_error: 15059.8145 - val_mean_squared_error: 317219296.0000
Epoch 4/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 12804.8037 - mean_absolute_error: 12804.8037 - mean_squared_error: 213327712.0000 - val_loss: 15013.7432 - val_mean_absolute_error: 15013.7432 - val_mean_squared_error: 315822528.0000
Epoch 5/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 12685.1836 - mean_absolute_error: 12685.1836 - mean_squared_error: 216693712.0000 - val_loss: 14897.5664 - val_mean_absolute_error: 14897.5664 - val_mean_squared_error: 312321536.0000
Epoch 6/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 13070.7646 - mean_absolute_error: 13070.7646 - mean_squared_error: 226325568.0000 - val_loss: 14624.8115 - val_mean_absolute_error: 14624.8115 - val_mean_squared_error: 304211456.0000
Epoch 7/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 11677.3457 - mean_absolute_error: 11677.3457 - mean_squared_error: 182421536.0000 - val_loss: 14033.1523 - val_mean_absolute_error: 14033.1523 - val_mean_squared_error: 287552000.0000
Epoch 8/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 11587.7676 - mean_absolute_error: 11587.7676 - mean_squared_error: 186459712.0000 - val_loss: 12811.5088 - val_mean_absolute_error: 12811.5088 - val_mean_squared_error: 255388784.0000
Epoch 9/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 10247.9883 - mean_absolute_error: 10247.9883 - mean_squared_error: 162383024.0000 - val_loss: 10429.5176 - val_mean_absolute_error: 10429.5176 - val_mean_squared_error: 201369584.0000
Epoch 10/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 7604.3228 - mean_absolute_error: 7604.3228 - mean_squared_error: 113054480.0000 - val_loss: 7842.7568 - val_mean_absolute_error: 7842.7568 - val_mean_squared_error: 130908048.0000
Epoch 11/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 5452.6167 - mean_absolute_error: 5452.6167 - mean_squared_error: 64783360.0000 - val_loss: 6443.2300 - val_mean_absolute_error: 6443.2300 - val_mean_squared_error: 76528304.0000
Epoch 12/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 5577.5264 - mean_absolute_error: 5577.5264 - mean_squared_error: 48421328.0000 - val_loss: 5156.3496 - val_mean_absolute_error: 5156.3496 - val_mean_squared_error: 46906576.0000
Epoch 13/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 4185.8662 - mean_absolute_error: 4185.8662 - mean_squared_error: 28402492.0000 - val_loss: 3831.1597 - val_mean_absolute_error: 3831.1597 - val_mean_squared_error: 39005828.0000
Epoch 14/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 2834.9033 - mean_absolute_error: 2834.9033 - mean_squared_error: 22312174.0000 - val_loss: 3447.4312 - val_mean_absolute_error: 3447.4312 - val_mean_squared_error: 33048548.0000
Epoch 15/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 2028.5846 - mean_absolute_error: 2028.5846 - mean_squared_error: 11924836.0000 - val_loss: 2607.2046 - val_mean_absolute_error: 2607.2046 - val_mean_squared_error: 15673783.0000
Epoch 16/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2132.9663 - mean_absolute_error: 2132.9663 - mean_squared_error: 10299200.0000 - val_loss: 2456.4429 - val_mean_absolute_error: 2456.4429 - val_mean_squared_error: 12376733.0000
Epoch 17/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 2229.5303 - mean_absolute_error: 2229.5303 - mean_squared_error: 10422261.0000 - val_loss: 2456.5820 - val_mean_absolute_error: 2456.5820 - val_mean_squared_error: 11495405.0000
Epoch 18/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 2110.2825 - mean_absolute_error: 2110.2825 - mean_squared_error: 9673548.0000 - val_loss: 2702.3467 - val_mean_absolute_error: 2702.3467 - val_mean_squared_error: 14017830.0000
Epoch 19/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1918.7455 - mean_absolute_error: 1918.7455 - mean_squared_error: 9766334.0000 - val_loss: 2392.4426 - val_mean_absolute_error: 2392.4426 - val_mean_squared_error: 12604962.0000
Epoch 20/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1767.8326 - mean_absolute_error: 1767.8326 - mean_squared_error: 7742549.5000 - val_loss: 2449.2893 - val_mean_absolute_error: 2449.2893 - val_mean_squared_error: 14135687.0000
Epoch 21/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1668.8171 - mean_absolute_error: 1668.8171 - mean_squared_error: 8648262.0000 - val_loss: 2985.9600 - val_mean_absolute_error: 2985.9600 - val_mean_squared_error: 22032380.0000
Epoch 22/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1572.0131 - mean_absolute_error: 1572.0131 - mean_squared_error: 8097240.5000 - val_loss: 2654.0725 - val_mean_absolute_error: 2654.0725 - val_mean_squared_error: 17470234.0000
Epoch 23/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1550.6599 - mean_absolute_error: 1550.6599 - mean_squared_error: 7738016.5000 - val_loss: 2477.0945 - val_mean_absolute_error: 2477.0945 - val_mean_squared_error: 14788380.0000
Epoch 24/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1439.6873 - mean_absolute_error: 1439.6873 - mean_squared_error: 6068495.0000 - val_loss: 2539.3716 - val_mean_absolute_error: 2539.3716 - val_mean_squared_error: 15306967.0000
Epoch 25/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1424.4299 - mean_absolute_error: 1424.4299 - mean_squared_error: 7035054.5000 - val_loss: 2308.9431 - val_mean_absolute_error: 2308.9431 - val_mean_squared_error: 11812677.0000
Epoch 26/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1391.7623 - mean_absolute_error: 1391.7623 - mean_squared_error: 4707238.5000 - val_loss: 2320.3286 - val_mean_absolute_error: 2320.3286 - val_mean_squared_error: 11592882.0000
Epoch 27/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1297.4465 - mean_absolute_error: 1297.4465 - mean_squared_error: 5581829.0000 - val_loss: 2652.3845 - val_mean_absolute_error: 2652.3845 - val_mean_squared_error: 15593551.0000
Epoch 28/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1555.2112 - mean_absolute_error: 1555.2112 - mean_squared_error: 7609448.0000 - val_loss: 2592.0962 - val_mean_absolute_error: 2592.0962 - val_mean_squared_error: 15392940.0000
Epoch 29/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1356.9624 - mean_absolute_error: 1356.9624 - mean_squared_error: 6572042.5000 - val_loss: 2389.3257 - val_mean_absolute_error: 2389.3257 - val_mean_squared_error: 12693088.0000
Epoch 30/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 1206.6702 - mean_absolute_error: 1206.6702 - mean_squared_error: 4003406.7500 - val_loss: 2413.5293 - val_mean_absolute_error: 2413.5293 - val_mean_squared_error: 13012541.0000
Epoch 31/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - loss: 1210.5659 - mean_absolute_error: 1210.5659 - mean_squared_error: 5018764.0000 - val_loss: 2214.9407 - val_mean_absolute_error: 2214.9407 - val_mean_squared_error: 10782924.0000
Epoch 32/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1097.8232 - mean_absolute_error: 1097.8232 - mean_squared_error: 3898326.7500 - val_loss: 2263.2910 - val_mean_absolute_error: 2263.2910 - val_mean_squared_error: 11351362.0000
Epoch 33/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1035.1315 - mean_absolute_error: 1035.1315 - mean_squared_error: 3874745.5000 - val_loss: 2361.9902 - val_mean_absolute_error: 2361.9902 - val_mean_squared_error: 12540764.0000
Epoch 34/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1025.2870 - mean_absolute_error: 1025.2870 - mean_squared_error: 3662750.0000 - val_loss: 2301.0029 - val_mean_absolute_error: 2301.0029 - val_mean_squared_error: 11688936.0000
Epoch 35/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 941.0439 - mean_absolute_error: 941.0439 - mean_squared_error: 3468902.7500 - val_loss: 2472.9702 - val_mean_absolute_error: 2472.9702 - val_mean_squared_error: 13929116.0000
Epoch 36/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 1013.9866 - mean_absolute_error: 1013.9866 - mean_squared_error: 4151086.2500 - val_loss: 2254.8440 - val_mean_absolute_error: 2254.8440 - val_mean_squared_error: 11275525.0000
Epoch 37/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 894.2857 - mean_absolute_error: 894.2857 - mean_squared_error: 2480004.7500 - val_loss: 2359.1851 - val_mean_absolute_error: 2359.1851 - val_mean_squared_error: 12606367.0000
Epoch 38/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 917.7911 - mean_absolute_error: 917.7911 - mean_squared_error: 2720528.7500 - val_loss: 2316.7498 - val_mean_absolute_error: 2316.7498 - val_mean_squared_error: 12084774.0000
Epoch 39/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 874.1887 - mean_absolute_error: 874.1887 - mean_squared_error: 2733795.7500 - val_loss: 2279.8594 - val_mean_absolute_error: 2279.8594 - val_mean_squared_error: 11469399.0000
Epoch 40/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 839.4818 - mean_absolute_error: 839.4818 - mean_squared_error: 2394648.5000 - val_loss: 2283.0730 - val_mean_absolute_error: 2283.0730 - val_mean_squared_error: 11269510.0000
Epoch 41/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 862.6512 - mean_absolute_error: 862.6512 - mean_squared_error: 2536404.5000 - val_loss: 2177.2109 - val_mean_absolute_error: 2177.2109 - val_mean_squared_error: 10285526.0000
Epoch 42/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 776.8596 - mean_absolute_error: 776.8596 - mean_squared_error: 1876070.0000 - val_loss: 2463.6228 - val_mean_absolute_error: 2463.6228 - val_mean_squared_error: 13681511.0000
Epoch 43/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1002.8488 - mean_absolute_error: 1002.8488 - mean_squared_error: 2881549.5000 - val_loss: 2242.1238 - val_mean_absolute_error: 2242.1238 - val_mean_squared_error: 11402226.0000
Epoch 44/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 839.5414 - mean_absolute_error: 839.5414 - mean_squared_error: 1901303.3750 - val_loss: 2228.2988 - val_mean_absolute_error: 2228.2988 - val_mean_squared_error: 10724634.0000
Epoch 45/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 962.5288 - mean_absolute_error: 962.5288 - mean_squared_error: 2567428.0000 - val_loss: 2131.9307 - val_mean_absolute_error: 2131.9307 - val_mean_squared_error: 9561860.0000
Epoch 46/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 860.7156 - mean_absolute_error: 860.7156 - mean_squared_error: 1626144.7500 - val_loss: 2115.5344 - val_mean_absolute_error: 2115.5344 - val_mean_squared_error: 9890322.0000
Epoch 47/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 812.0605 - mean_absolute_error: 812.0605 - mean_squared_error: 1993160.0000 - val_loss: 2183.4006 - val_mean_absolute_error: 2183.4006 - val_mean_squared_error: 11100919.0000
Epoch 48/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 829.8817 - mean_absolute_error: 829.8817 - mean_squared_error: 1888040.3750 - val_loss: 2158.8330 - val_mean_absolute_error: 2158.8330 - val_mean_squared_error: 10138576.0000
Epoch 49/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 670.5828 - mean_absolute_error: 670.5828 - mean_squared_error: 1410650.0000 - val_loss: 2184.4258 - val_mean_absolute_error: 2184.4258 - val_mean_squared_error: 9538737.0000
Epoch 50/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 714.9945 - mean_absolute_error: 714.9945 - mean_squared_error: 1208977.6250 - val_loss: 2101.0571 - val_mean_absolute_error: 2101.0571 - val_mean_squared_error: 8698258.0000
Epoch 51/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 770.4973 - mean_absolute_error: 770.4973 - mean_squared_error: 1403904.3750 - val_loss: 2248.7883 - val_mean_absolute_error: 2248.7883 - val_mean_squared_error: 9786332.0000
Epoch 52/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 714.8465 - mean_absolute_error: 714.8465 - mean_squared_error: 1382226.3750 - val_loss: 2187.4890 - val_mean_absolute_error: 2187.4890 - val_mean_squared_error: 9228258.0000
Epoch 53/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 767.1041 - mean_absolute_error: 767.1041 - mean_squared_error: 1005766.0625 - val_loss: 2166.3457 - val_mean_absolute_error: 2166.3457 - val_mean_squared_error: 9308290.0000
Epoch 54/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 591.4105 - mean_absolute_error: 591.4105 - mean_squared_error: 900808.1250 - val_loss: 2121.0000 - val_mean_absolute_error: 2121.0000 - val_mean_squared_error: 8788503.0000
Epoch 55/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 545.9203 - mean_absolute_error: 545.9203 - mean_squared_error: 818345.7500 - val_loss: 2069.8994 - val_mean_absolute_error: 2069.8994 - val_mean_squared_error: 8524100.0000
Epoch 56/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 589.8349 - mean_absolute_error: 589.8349 - mean_squared_error: 870123.9375 - val_loss: 2212.5356 - val_mean_absolute_error: 2212.5356 - val_mean_squared_error: 9571247.0000
Epoch 57/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 664.1595 - mean_absolute_error: 664.1595 - mean_squared_error: 825561.9375 - val_loss: 2094.3467 - val_mean_absolute_error: 2094.3467 - val_mean_squared_error: 8782165.0000
Epoch 58/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 599.9980 - mean_absolute_error: 599.9980 - mean_squared_error: 817989.2500 - val_loss: 2155.7905 - val_mean_absolute_error: 2155.7905 - val_mean_squared_error: 9383756.0000
Epoch 59/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 548.5370 - mean_absolute_error: 548.5370 - mean_squared_error: 791018.1250 - val_loss: 2103.5129 - val_mean_absolute_error: 2103.5129 - val_mean_squared_error: 8979621.0000
Epoch 60/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 468.1558 - mean_absolute_error: 468.1558 - mean_squared_error: 604980.3125 - val_loss: 2110.2000 - val_mean_absolute_error: 2110.2000 - val_mean_squared_error: 9224394.0000
Epoch 61/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 536.1251 - mean_absolute_error: 536.1251 - mean_squared_error: 714055.1250 - val_loss: 2175.2014 - val_mean_absolute_error: 2175.2014 - val_mean_squared_error: 9869168.0000
Epoch 62/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 632.2540 - mean_absolute_error: 632.2540 - mean_squared_error: 825396.2500 - val_loss: 2113.2356 - val_mean_absolute_error: 2113.2356 - val_mean_squared_error: 9461128.0000
Epoch 63/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 461.8608 - mean_absolute_error: 461.8608 - mean_squared_error: 563021.1875 - val_loss: 2073.4121 - val_mean_absolute_error: 2073.4121 - val_mean_squared_error: 8864295.0000
Epoch 64/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 435.9915 - mean_absolute_error: 435.9915 - mean_squared_error: 511521.5312 - val_loss: 2103.7532 - val_mean_absolute_error: 2103.7532 - val_mean_squared_error: 9011646.0000
Epoch 65/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 412.2960 - mean_absolute_error: 412.2960 - mean_squared_error: 471465.5000 - val_loss: 2152.4851 - val_mean_absolute_error: 2152.4851 - val_mean_squared_error: 9611580.0000
Epoch 66/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 573.7694 - mean_absolute_error: 573.7694 - mean_squared_error: 747110.0625 - val_loss: 2068.9834 - val_mean_absolute_error: 2068.9834 - val_mean_squared_error: 8655478.0000
Epoch 67/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - loss: 521.0813 - mean_absolute_error: 521.0813 - mean_squared_error: 572716.5000 - val_loss: 2252.1548 - val_mean_absolute_error: 2252.1548 - val_mean_squared_error: 10550101.0000
Epoch 68/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 709.4558 - mean_absolute_error: 709.4558 - mean_squared_error: 977237.3125 - val_loss: 2113.0811 - val_mean_absolute_error: 2113.0811 - val_mean_squared_error: 9076281.0000
Epoch 69/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 539.5905 - mean_absolute_error: 539.5905 - mean_squared_error: 654407.6250 - val_loss: 2141.9570 - val_mean_absolute_error: 2141.9570 - val_mean_squared_error: 9493237.0000
Epoch 70/70
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 472.9179 - mean_absolute_error: 472.9179 - mean_squared_error: 539581.1875 - val_loss: 2059.5227 - val_mean_absolute_error: 2059.5227 - val_mean_squared_error: 8696952.0000

In [ ]:
# Model Evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Predict on test data
y_pred = model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print results
print(f"Mean Absolute Error: {mae}")
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")


# Example New Data
new_data = X.iloc[[0]]

# Apply preprocessing
new_data_processed = preprocessor.transform(new_data)

# Predict price
predicted_price = model.predict(new_data_processed)

print(f"Predicted Price: {predicted_price[0][0]}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 866ms/step
Mean Absolute Error: 1735.7369710365854
Mean Squared Error: 7678718.991172119
R-squared: 0.9027321017398193
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 721ms/step
Predicted Price: 13347.0986328125